package com.everis.practicaspringcloudcompra.model;
// Generated 25/09/2019 03:21:43 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Inventario generated by hbm2java
 */
@Entity
@Table(name = "inventario", catalog = "mydb")
public class Inventario implements java.io.Serializable {

	private int id;
	private String nombre;
	private int stock;
	private int port;
	@JsonIgnore
	private Set<Compra> compras = new HashSet<Compra>(0);

	public Inventario() {
	}

	public Inventario(int id, String nombre, int stock, int port) {
		this.id = id;
		this.nombre = nombre;
		this.stock = stock;
		this.port = port;
	}

	public Inventario(int id, String nombre, int stock, int port, Set<Compra> compras) {
		this.id = id;
		this.nombre = nombre;
		this.stock = stock;
		this.port = port;
		this.compras = compras;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "stock", nullable = false)
	public int getStock() {
		return this.stock;
	}

	public void setStock(int stock) {
		this.stock = stock;
	}

	@Column(name = "port", nullable = false)
	public int getPort() {
		return this.port;
	}

	public void setPort(int port) {
		this.port = port;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "inventario")
	public Set<Compra> getCompras() {
		return this.compras;
	}

	public void setCompras(Set<Compra> compras) {
		this.compras = compras;
	}

}
